#spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issue?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    password:
    port: 6379


  resources:
    static-locations: classpath:/templates/,classpath:/static/
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
#    端口配置
server:
  port: 8181
#     mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml